/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import Apuesta.Apuesta;
import Apuesta.IngresoApuesta;
import datos.CargaDatos;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import manejadores.ManejadorIngresoApuesta;

/**
 *
 * @author luis
 */
public class CargaApuestas extends javax.swing.JFrame {
    
    private String archivoALeer;
    private Apuesta apuestas[]= new Apuesta[0];
    private ManejadorIngresoApuesta manejador  = new ManejadorIngresoApuesta();
    
    /**
     * Creates new form CargaApuestas
     */
    public CargaApuestas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        monto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        quintoLugar = new javax.swing.JComboBox<>();
        primerLugar = new javax.swing.JComboBox<>();
        segundoLugar = new javax.swing.JComboBox<>();
        tercerLugar = new javax.swing.JComboBox<>();
        cuartoLugar = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        decimoLugar = new javax.swing.JComboBox<>();
        sextoLugar = new javax.swing.JComboBox<>();
        septimoLugar = new javax.swing.JComboBox<>();
        octavoLugar = new javax.swing.JComboBox<>();
        novenoLugar = new javax.swing.JComboBox<>();
        Regresar = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Purisa", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INGRESO DE APUESTAS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 700, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/—Pngtree—horse racing vector logo design_5290315 (2)-modified.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 130, 90));

        jLabel4.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("o hazlo a través de una carga de archivos.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 20));

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("CERRAR APUESTAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 240, 100));

        jLabel5.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese el Orden en el que considera que llegaran los Caballos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        jLabel6.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Monto Apostar:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, 30));

        nombre.setBackground(new java.awt.Color(51, 102, 255));
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreKeyPressed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 200, 30));

        jLabel7.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("5° Lugar");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        monto.setBackground(new java.awt.Color(51, 102, 255));
        monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                montoKeyPressed(evt);
            }
        });
        getContentPane().add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 200, 30));

        jLabel8.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Agrega una Apuesta de manera manual agregando los datos correspondientes a la apuesta ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        jLabel9.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre Apostante:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("1° Lugar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("2° Lugar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, -1));

        jLabel12.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("3° Lugar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("4° Lugar");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, -1, -1));

        quintoLugar.setBackground(new java.awt.Color(51, 102, 255));
        quintoLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        quintoLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                quintoLugarKeyPressed(evt);
            }
        });
        getContentPane().add(quintoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 50, -1));

        primerLugar.setBackground(new java.awt.Color(51, 102, 255));
        primerLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        primerLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                primerLugarKeyPressed(evt);
            }
        });
        getContentPane().add(primerLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 50, -1));

        segundoLugar.setBackground(new java.awt.Color(51, 102, 255));
        segundoLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        segundoLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                segundoLugarKeyPressed(evt);
            }
        });
        getContentPane().add(segundoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 50, -1));

        tercerLugar.setBackground(new java.awt.Color(51, 102, 255));
        tercerLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        tercerLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tercerLugarKeyPressed(evt);
            }
        });
        getContentPane().add(tercerLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 50, -1));

        cuartoLugar.setBackground(new java.awt.Color(51, 102, 255));
        cuartoLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cuartoLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cuartoLugarKeyPressed(evt);
            }
        });
        getContentPane().add(cuartoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 50, -1));

        jLabel14.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("10° Lugar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        jLabel15.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("6° Lugar");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, -1, -1));

        jLabel16.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("7° Lugar");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, -1));

        jLabel17.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("8° Lugar");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        jLabel18.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("9° Lugar");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, -1, -1));

        decimoLugar.setBackground(new java.awt.Color(51, 102, 255));
        decimoLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        decimoLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                decimoLugarKeyPressed(evt);
            }
        });
        getContentPane().add(decimoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 50, -1));

        sextoLugar.setBackground(new java.awt.Color(51, 102, 255));
        sextoLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        sextoLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sextoLugarKeyPressed(evt);
            }
        });
        getContentPane().add(sextoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 50, -1));

        septimoLugar.setBackground(new java.awt.Color(51, 102, 255));
        septimoLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        septimoLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                septimoLugarKeyPressed(evt);
            }
        });
        getContentPane().add(septimoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 50, -1));

        octavoLugar.setBackground(new java.awt.Color(51, 102, 255));
        octavoLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        octavoLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                octavoLugarKeyPressed(evt);
            }
        });
        getContentPane().add(octavoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 50, -1));

        novenoLugar.setBackground(new java.awt.Color(51, 102, 255));
        novenoLugar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        novenoLugar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                novenoLugarKeyPressed(evt);
            }
        });
        getContentPane().add(novenoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 50, -1));

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        Regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegresarMouseClicked(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 560, -1, -1));

        jLabel19.setFont(new java.awt.Font("Ubuntu", 3, 15)); // NOI18N
        jLabel19.setText("REGRESAR");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 640, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Guardar Apuesta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 240, 100));

        jButton3.setBackground(new java.awt.Color(51, 102, 255));
        jButton3.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Cargar Archivo Entrada");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 240, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoCliente.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.out.println(apuestas.length);
        boolean hayNulo=false;
        if (this.apuestas != null) {
            this.apuestas = manejador.verificarApuestasIngresadas(apuestas);
            //this.reporte.setTimpoPormedioVerificacion(this.verificador.getTiempoPromedioVerificacion());
            
            
            
            if(this.apuestas.length!=0){
                System.out.println(apuestas.length);
                for (int i = 0; i < apuestas.length; i++) {
                     if(apuestas[i]==null){
                        hayNulo=true;
                    }
                }
                if(hayNulo==true){
                    this.apuestas = manejador.quitarNulos(apuestas);
                    if(this.apuestas.length!=0){
                        IngresoResultados ingreso = new IngresoResultados(this.apuestas);
                        ingreso.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "No ha sido ingresada ninguna apuesta valida", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    IngresoResultados ingreso = new IngresoResultados(this.apuestas);
                    ingreso.setVisible(true);
                    this.dispose();
                }
                
            } else {
                 JOptionPane.showMessageDialog(this, "No ha sido ingresada ninguna apuesta valida", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Aun no hay apuestas registradas en el sistema", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        System.out.println(apuestas.length);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void RegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegresarMouseClicked
        //Regresamos al menú de manejadores
        int response = JOptionPane.showConfirmDialog(this,"¿Quieres Regresar al inicio", "Regresar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (response==JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Regresando...");
            //Cerramos esta ventana y procedemos a mostrar el menu manejadores
            this.setVisible(false);
            VentanaPrincipal ventana = new VentanaPrincipal();
            ventana.setVisible(true);
        }
    }//GEN-LAST:event_RegresarMouseClicked

    private void montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyTyped
        char validar=evt.getKeyChar();
        if (Character.isLetter(validar)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresar solo números");
        }
    }//GEN-LAST:event_montoKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        apuestas = manejador.guardarDatos(nombre.getText(), monto.getText(), posicionesCarreraCaballos(), apuestas);
        reiniciarVariables();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        apuestas=manejador.cargarDatos(this, archivoALeer, apuestas);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
             monto.requestFocus();
        }
    }//GEN-LAST:event_nombreKeyPressed

    private void montoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            primerLugar.requestFocus();
        }
    }//GEN-LAST:event_montoKeyPressed

    private void primerLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_primerLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            segundoLugar.requestFocus();
        }
    }//GEN-LAST:event_primerLugarKeyPressed

    private void segundoLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_segundoLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            tercerLugar.requestFocus();
        }
    }//GEN-LAST:event_segundoLugarKeyPressed

    private void tercerLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tercerLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            cuartoLugar.requestFocus();
        }
    }//GEN-LAST:event_tercerLugarKeyPressed

    private void cuartoLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cuartoLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            quintoLugar.requestFocus();
        }
    }//GEN-LAST:event_cuartoLugarKeyPressed

    private void quintoLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quintoLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            sextoLugar.requestFocus();
        }
    }//GEN-LAST:event_quintoLugarKeyPressed

    private void sextoLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sextoLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            septimoLugar.requestFocus();
        }
    }//GEN-LAST:event_sextoLugarKeyPressed

    private void septimoLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_septimoLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            octavoLugar.requestFocus();
        }
    }//GEN-LAST:event_septimoLugarKeyPressed

    private void octavoLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_octavoLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            novenoLugar.requestFocus();
        }
    }//GEN-LAST:event_octavoLugarKeyPressed

    private void novenoLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_novenoLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            decimoLugar.requestFocus();
        }
    }//GEN-LAST:event_novenoLugarKeyPressed

    private void decimoLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_decimoLugarKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_decimoLugarKeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_RIGHT){
            jButton3.requestFocus();
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_LEFT){
            jButton2.requestFocus();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private int[] posicionesCarreraCaballos() {
        int[] posiciones = {manejador.parserCombo(primerLugar),manejador.parserCombo(segundoLugar), manejador.parserCombo(tercerLugar), manejador.parserCombo(cuartoLugar), manejador.parserCombo(quintoLugar), manejador.parserCombo(sextoLugar), manejador.parserCombo(septimoLugar), manejador.parserCombo(octavoLugar), manejador.parserCombo(novenoLugar), manejador.parserCombo(decimoLugar)};
        return posiciones;
    }
    
    private void reiniciarVariables(){
        nombre.setText("");
        monto.setText("");
        primerLugar.setSelectedIndex(0);
        segundoLugar.setSelectedIndex(0);
        tercerLugar.setSelectedIndex(0);
        cuartoLugar.setSelectedIndex(0);
        quintoLugar.setSelectedIndex(0);
        sextoLugar.setSelectedIndex(0);
        septimoLugar.setSelectedIndex(0);
        octavoLugar.setSelectedIndex(0);
        novenoLugar.setSelectedIndex(0);
        decimoLugar.setSelectedIndex(0);
        nombre.requestFocus();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Regresar;
    private javax.swing.JComboBox<String> cuartoLugar;
    private javax.swing.JComboBox<String> decimoLugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> novenoLugar;
    private javax.swing.JComboBox<String> octavoLugar;
    private javax.swing.JComboBox<String> primerLugar;
    private javax.swing.JComboBox<String> quintoLugar;
    private javax.swing.JComboBox<String> segundoLugar;
    private javax.swing.JComboBox<String> septimoLugar;
    private javax.swing.JComboBox<String> sextoLugar;
    private javax.swing.JComboBox<String> tercerLugar;
    // End of variables declaration//GEN-END:variables
}
